# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "vmw_pvscsi" "uhci_hcd" "ehci_pci" "ahci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f2d04239-faf5-45d1-b883-bef0d4497b32";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/641B-7766";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/universalis-data" = {
    device = "/dev/disk/by-uuid/6b41edcd-61f0-4907-bb47-d117d300e1bd";
    fsType = "ext4";
    options = [ "defaults" "nofail" "x-systemd.device-timeout=10" ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
